name = "Hello friend"
description = "Ported from hugo-hello-friend theme"
license = "MIT"
homepage = ""
min_version = "0.12.0"
demo = ""

[extra]

[author]
name = "Miyaco"
homepage = "https://twitter.com/MiyacoPl"

[original]
author = "panr"
homepage = "https://twitter.com/panr"
repo = "https://github.com/panr/hugo-theme-hello-friend"
